// Generated by gencpp from file schunk_ezn64/acknowledge_error.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_ACKNOWLEDGE_ERROR_H
#define SCHUNK_EZN64_MESSAGE_ACKNOWLEDGE_ERROR_H

#include <ros/service_traits.h>


#include <schunk_ezn64/acknowledge_errorRequest.h>
#include <schunk_ezn64/acknowledge_errorResponse.h>


namespace schunk_ezn64
{

struct acknowledge_error
{

typedef acknowledge_errorRequest Request;
typedef acknowledge_errorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct acknowledge_error
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::acknowledge_error > {
  static const char* value()
  {
    return "216312424a7b13297dba83de8033144e";
  }

  static const char* value(const ::schunk_ezn64::acknowledge_error&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::acknowledge_error > {
  static const char* value()
  {
    return "schunk_ezn64/acknowledge_error";
  }

  static const char* value(const ::schunk_ezn64::acknowledge_error&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::acknowledge_errorRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::acknowledge_error >
template<>
struct MD5Sum< ::schunk_ezn64::acknowledge_errorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::acknowledge_error >::value();
  }
  static const char* value(const ::schunk_ezn64::acknowledge_errorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::acknowledge_errorRequest> should match
// service_traits::DataType< ::schunk_ezn64::acknowledge_error >
template<>
struct DataType< ::schunk_ezn64::acknowledge_errorRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::acknowledge_error >::value();
  }
  static const char* value(const ::schunk_ezn64::acknowledge_errorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::acknowledge_errorResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::acknowledge_error >
template<>
struct MD5Sum< ::schunk_ezn64::acknowledge_errorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::acknowledge_error >::value();
  }
  static const char* value(const ::schunk_ezn64::acknowledge_errorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::acknowledge_errorResponse> should match
// service_traits::DataType< ::schunk_ezn64::acknowledge_error >
template<>
struct DataType< ::schunk_ezn64::acknowledge_errorResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::acknowledge_error >::value();
  }
  static const char* value(const ::schunk_ezn64::acknowledge_errorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_ACKNOWLEDGE_ERROR_H
