// Generated by gencpp from file schunk_ezn64/fastStop.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_FASTSTOP_H
#define SCHUNK_EZN64_MESSAGE_FASTSTOP_H

#include <ros/service_traits.h>


#include <schunk_ezn64/fastStopRequest.h>
#include <schunk_ezn64/fastStopResponse.h>


namespace schunk_ezn64
{

struct fastStop
{

typedef fastStopRequest Request;
typedef fastStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fastStop
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::fastStop > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::schunk_ezn64::fastStop&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::fastStop > {
  static const char* value()
  {
    return "schunk_ezn64/fastStop";
  }

  static const char* value(const ::schunk_ezn64::fastStop&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::fastStopRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::fastStop >
template<>
struct MD5Sum< ::schunk_ezn64::fastStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::fastStop >::value();
  }
  static const char* value(const ::schunk_ezn64::fastStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::fastStopRequest> should match
// service_traits::DataType< ::schunk_ezn64::fastStop >
template<>
struct DataType< ::schunk_ezn64::fastStopRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::fastStop >::value();
  }
  static const char* value(const ::schunk_ezn64::fastStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::fastStopResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::fastStop >
template<>
struct MD5Sum< ::schunk_ezn64::fastStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::fastStop >::value();
  }
  static const char* value(const ::schunk_ezn64::fastStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::fastStopResponse> should match
// service_traits::DataType< ::schunk_ezn64::fastStop >
template<>
struct DataType< ::schunk_ezn64::fastStopResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::fastStop >::value();
  }
  static const char* value(const ::schunk_ezn64::fastStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_FASTSTOP_H
