// Generated by gencpp from file schunk_ezn64/get_errorResponse.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_GET_ERRORRESPONSE_H
#define SCHUNK_EZN64_MESSAGE_GET_ERRORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_ezn64
{
template <class ContainerAllocator>
struct get_errorResponse_
{
  typedef get_errorResponse_<ContainerAllocator> Type;

  get_errorResponse_()
    : error_code(0)  {
    }
  get_errorResponse_(const ContainerAllocator& _alloc)
    : error_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_errorResponse_

typedef ::schunk_ezn64::get_errorResponse_<std::allocator<void> > get_errorResponse;

typedef boost::shared_ptr< ::schunk_ezn64::get_errorResponse > get_errorResponsePtr;
typedef boost::shared_ptr< ::schunk_ezn64::get_errorResponse const> get_errorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_ezn64::get_errorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::schunk_ezn64::get_errorResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::get_errorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::schunk_ezn64::get_errorResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::get_errorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace schunk_ezn64

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea324a22c787839f822b9a025bc2c6fe";
  }

  static const char* value(const ::schunk_ezn64::get_errorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea324a22c787839fULL;
  static const uint64_t static_value2 = 0x822b9a025bc2c6feULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_ezn64/get_errorResponse";
  }

  static const char* value(const ::schunk_ezn64::get_errorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 error_code\n"
"\n"
;
  }

  static const char* value(const ::schunk_ezn64::get_errorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_errorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_ezn64::get_errorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_ezn64::get_errorResponse_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_GET_ERRORRESPONSE_H
