// Generated by gencpp from file schunk_ezn64/get_velocity.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_GET_VELOCITY_H
#define SCHUNK_EZN64_MESSAGE_GET_VELOCITY_H

#include <ros/service_traits.h>


#include <schunk_ezn64/get_velocityRequest.h>
#include <schunk_ezn64/get_velocityResponse.h>


namespace schunk_ezn64
{

struct get_velocity
{

typedef get_velocityRequest Request;
typedef get_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_velocity
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::get_velocity > {
  static const char* value()
  {
    return "4372144f5734356a08e3014ad0d9d0cf";
  }

  static const char* value(const ::schunk_ezn64::get_velocity&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::get_velocity > {
  static const char* value()
  {
    return "schunk_ezn64/get_velocity";
  }

  static const char* value(const ::schunk_ezn64::get_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::get_velocityRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::get_velocity >
template<>
struct MD5Sum< ::schunk_ezn64::get_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::get_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::get_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::get_velocityRequest> should match
// service_traits::DataType< ::schunk_ezn64::get_velocity >
template<>
struct DataType< ::schunk_ezn64::get_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::get_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::get_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::get_velocityResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::get_velocity >
template<>
struct MD5Sum< ::schunk_ezn64::get_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::get_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::get_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::get_velocityResponse> should match
// service_traits::DataType< ::schunk_ezn64::get_velocity >
template<>
struct DataType< ::schunk_ezn64::get_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::get_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::get_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_GET_VELOCITY_H
