// Generated by gencpp from file schunk_ezn64/get_velocityResponse.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_GET_VELOCITYRESPONSE_H
#define SCHUNK_EZN64_MESSAGE_GET_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_ezn64
{
template <class ContainerAllocator>
struct get_velocityResponse_
{
  typedef get_velocityResponse_<ContainerAllocator> Type;

  get_velocityResponse_()
    : actual_velocity(0.0)  {
    }
  get_velocityResponse_(const ContainerAllocator& _alloc)
    : actual_velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _actual_velocity_type;
  _actual_velocity_type actual_velocity;





  typedef boost::shared_ptr< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_velocityResponse_

typedef ::schunk_ezn64::get_velocityResponse_<std::allocator<void> > get_velocityResponse;

typedef boost::shared_ptr< ::schunk_ezn64::get_velocityResponse > get_velocityResponsePtr;
typedef boost::shared_ptr< ::schunk_ezn64::get_velocityResponse const> get_velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.actual_velocity == rhs.actual_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace schunk_ezn64

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4372144f5734356a08e3014ad0d9d0cf";
  }

  static const char* value(const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4372144f5734356aULL;
  static const uint64_t static_value2 = 0x08e3014ad0d9d0cfULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_ezn64/get_velocityResponse";
  }

  static const char* value(const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 actual_velocity\n"
"\n"
;
  }

  static const char* value(const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actual_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_ezn64::get_velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_ezn64::get_velocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "actual_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.actual_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_GET_VELOCITYRESPONSE_H
