// Generated by gencpp from file schunk_ezn64/PosAndSpeedFloat32.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_POSANDSPEEDFLOAT32_H
#define SCHUNK_EZN64_MESSAGE_POSANDSPEEDFLOAT32_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_ezn64
{
template <class ContainerAllocator>
struct PosAndSpeedFloat32_
{
  typedef PosAndSpeedFloat32_<ContainerAllocator> Type;

  PosAndSpeedFloat32_()
    : pos(0.0)
    , speed(0.0)  {
    }
  PosAndSpeedFloat32_(const ContainerAllocator& _alloc)
    : pos(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_type;
  _pos_type pos;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> const> ConstPtr;

}; // struct PosAndSpeedFloat32_

typedef ::schunk_ezn64::PosAndSpeedFloat32_<std::allocator<void> > PosAndSpeedFloat32;

typedef boost::shared_ptr< ::schunk_ezn64::PosAndSpeedFloat32 > PosAndSpeedFloat32Ptr;
typedef boost::shared_ptr< ::schunk_ezn64::PosAndSpeedFloat32 const> PosAndSpeedFloat32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator1> & lhs, const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator1> & lhs, const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace schunk_ezn64

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0611d9adb487c3bcf130e5b7b3ee7f37";
  }

  static const char* value(const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0611d9adb487c3bcULL;
  static const uint64_t static_value2 = 0xf130e5b7b3ee7f37ULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_ezn64/PosAndSpeedFloat32";
  }

  static const char* value(const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos\n"
"float32 speed\n"
;
  }

  static const char* value(const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosAndSpeedFloat32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_ezn64::PosAndSpeedFloat32_<ContainerAllocator>& v)
  {
    s << indent << "pos: ";
    Printer<float>::stream(s, indent + "  ", v.pos);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_POSANDSPEEDFLOAT32_H
