// Generated by gencpp from file schunk_ezn64/set_velocity.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_SET_VELOCITY_H
#define SCHUNK_EZN64_MESSAGE_SET_VELOCITY_H

#include <ros/service_traits.h>


#include <schunk_ezn64/set_velocityRequest.h>
#include <schunk_ezn64/set_velocityResponse.h>


namespace schunk_ezn64
{

struct set_velocity
{

typedef set_velocityRequest Request;
typedef set_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_velocity
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::set_velocity > {
  static const char* value()
  {
    return "8bcbe89faecc3b1502a1b95a8574cab4";
  }

  static const char* value(const ::schunk_ezn64::set_velocity&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::set_velocity > {
  static const char* value()
  {
    return "schunk_ezn64/set_velocity";
  }

  static const char* value(const ::schunk_ezn64::set_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::set_velocityRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::set_velocity >
template<>
struct MD5Sum< ::schunk_ezn64::set_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::set_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::set_velocityRequest> should match
// service_traits::DataType< ::schunk_ezn64::set_velocity >
template<>
struct DataType< ::schunk_ezn64::set_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::set_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::set_velocityResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::set_velocity >
template<>
struct MD5Sum< ::schunk_ezn64::set_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::set_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::set_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::set_velocityResponse> should match
// service_traits::DataType< ::schunk_ezn64::set_velocity >
template<>
struct DataType< ::schunk_ezn64::set_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::set_velocity >::value();
  }
  static const char* value(const ::schunk_ezn64::set_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_SET_VELOCITY_H
