// Generated by gencpp from file schunk_ezn64/set_positionResponse.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_SET_POSITIONRESPONSE_H
#define SCHUNK_EZN64_MESSAGE_SET_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace schunk_ezn64
{
template <class ContainerAllocator>
struct set_positionResponse_
{
  typedef set_positionResponse_<ContainerAllocator> Type;

  set_positionResponse_()
    : goal_accepted(false)  {
    }
  set_positionResponse_(const ContainerAllocator& _alloc)
    : goal_accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _goal_accepted_type;
  _goal_accepted_type goal_accepted;





  typedef boost::shared_ptr< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_positionResponse_

typedef ::schunk_ezn64::set_positionResponse_<std::allocator<void> > set_positionResponse;

typedef boost::shared_ptr< ::schunk_ezn64::set_positionResponse > set_positionResponsePtr;
typedef boost::shared_ptr< ::schunk_ezn64::set_positionResponse const> set_positionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_ezn64::set_positionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::schunk_ezn64::set_positionResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::set_positionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal_accepted == rhs.goal_accepted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::schunk_ezn64::set_positionResponse_<ContainerAllocator1> & lhs, const ::schunk_ezn64::set_positionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace schunk_ezn64

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a5ca3c440eebef45662a29c35d8e42e";
  }

  static const char* value(const ::schunk_ezn64::set_positionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a5ca3c440eebef4ULL;
  static const uint64_t static_value2 = 0x5662a29c35d8e42eULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_ezn64/set_positionResponse";
  }

  static const char* value(const ::schunk_ezn64::set_positionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool goal_accepted\n"
"\n"
;
  }

  static const char* value(const ::schunk_ezn64::set_positionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_positionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_ezn64::set_positionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_ezn64::set_positionResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_SET_POSITIONRESPONSE_H
