// Generated by gencpp from file schunk_ezn64/set_position.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_SET_POSITION_H
#define SCHUNK_EZN64_MESSAGE_SET_POSITION_H

#include <ros/service_traits.h>


#include <schunk_ezn64/set_positionRequest.h>
#include <schunk_ezn64/set_positionResponse.h>


namespace schunk_ezn64
{

struct set_position
{

typedef set_positionRequest Request;
typedef set_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_position
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::set_position > {
  static const char* value()
  {
    return "9d30216bd0f9755a614e054b1e5b684d";
  }

  static const char* value(const ::schunk_ezn64::set_position&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::set_position > {
  static const char* value()
  {
    return "schunk_ezn64/set_position";
  }

  static const char* value(const ::schunk_ezn64::set_position&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::set_positionRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::set_position >
template<>
struct MD5Sum< ::schunk_ezn64::set_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::set_position >::value();
  }
  static const char* value(const ::schunk_ezn64::set_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::set_positionRequest> should match
// service_traits::DataType< ::schunk_ezn64::set_position >
template<>
struct DataType< ::schunk_ezn64::set_positionRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::set_position >::value();
  }
  static const char* value(const ::schunk_ezn64::set_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::set_positionResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::set_position >
template<>
struct MD5Sum< ::schunk_ezn64::set_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::set_position >::value();
  }
  static const char* value(const ::schunk_ezn64::set_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::set_positionResponse> should match
// service_traits::DataType< ::schunk_ezn64::set_position >
template<>
struct DataType< ::schunk_ezn64::set_positionResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::set_position >::value();
  }
  static const char* value(const ::schunk_ezn64::set_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_SET_POSITION_H
