// Generated by gencpp from file schunk_ezn64/stop.msg
// DO NOT EDIT!


#ifndef SCHUNK_EZN64_MESSAGE_STOP_H
#define SCHUNK_EZN64_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <schunk_ezn64/stopRequest.h>
#include <schunk_ezn64/stopResponse.h>


namespace schunk_ezn64
{

struct stop
{

typedef stopRequest Request;
typedef stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop
} // namespace schunk_ezn64


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_ezn64::stop > {
  static const char* value()
  {
    return "1dc3c304d8e1ef4b9d7103ce1e3c990a";
  }

  static const char* value(const ::schunk_ezn64::stop&) { return value(); }
};

template<>
struct DataType< ::schunk_ezn64::stop > {
  static const char* value()
  {
    return "schunk_ezn64/stop";
  }

  static const char* value(const ::schunk_ezn64::stop&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_ezn64::stopRequest> should match
// service_traits::MD5Sum< ::schunk_ezn64::stop >
template<>
struct MD5Sum< ::schunk_ezn64::stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::stop >::value();
  }
  static const char* value(const ::schunk_ezn64::stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::stopRequest> should match
// service_traits::DataType< ::schunk_ezn64::stop >
template<>
struct DataType< ::schunk_ezn64::stopRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::stop >::value();
  }
  static const char* value(const ::schunk_ezn64::stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_ezn64::stopResponse> should match
// service_traits::MD5Sum< ::schunk_ezn64::stop >
template<>
struct MD5Sum< ::schunk_ezn64::stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_ezn64::stop >::value();
  }
  static const char* value(const ::schunk_ezn64::stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_ezn64::stopResponse> should match
// service_traits::DataType< ::schunk_ezn64::stop >
template<>
struct DataType< ::schunk_ezn64::stopResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_ezn64::stop >::value();
  }
  static const char* value(const ::schunk_ezn64::stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_EZN64_MESSAGE_STOP_H
