// Generated by gencpp from file wittenstein_msgs/wittenstein.msg
// DO NOT EDIT!


#ifndef WITTENSTEIN_MSGS_MESSAGE_WITTENSTEIN_H
#define WITTENSTEIN_MSGS_MESSAGE_WITTENSTEIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wittenstein_msgs
{
template <class ContainerAllocator>
struct wittenstein_
{
  typedef wittenstein_<ContainerAllocator> Type;

  wittenstein_()
    : fx(0.0)
    , fy(0.0)
    , fz(0.0)  {
    }
  wittenstein_(const ContainerAllocator& _alloc)
    : fx(0.0)
    , fy(0.0)
    , fz(0.0)  {
  (void)_alloc;
    }



   typedef double _fx_type;
  _fx_type fx;

   typedef double _fy_type;
  _fy_type fy;

   typedef double _fz_type;
  _fz_type fz;





  typedef boost::shared_ptr< ::wittenstein_msgs::wittenstein_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wittenstein_msgs::wittenstein_<ContainerAllocator> const> ConstPtr;

}; // struct wittenstein_

typedef ::wittenstein_msgs::wittenstein_<std::allocator<void> > wittenstein;

typedef boost::shared_ptr< ::wittenstein_msgs::wittenstein > wittensteinPtr;
typedef boost::shared_ptr< ::wittenstein_msgs::wittenstein const> wittensteinConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wittenstein_msgs::wittenstein_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wittenstein_msgs::wittenstein_<ContainerAllocator1> & lhs, const ::wittenstein_msgs::wittenstein_<ContainerAllocator2> & rhs)
{
  return lhs.fx == rhs.fx &&
    lhs.fy == rhs.fy &&
    lhs.fz == rhs.fz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wittenstein_msgs::wittenstein_<ContainerAllocator1> & lhs, const ::wittenstein_msgs::wittenstein_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wittenstein_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wittenstein_msgs::wittenstein_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wittenstein_msgs::wittenstein_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wittenstein_msgs::wittenstein_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7b2ae941c5b15bd5e80a4da6c8efa41";
  }

  static const char* value(const ::wittenstein_msgs::wittenstein_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7b2ae941c5b15bdULL;
  static const uint64_t static_value2 = 0x5e80a4da6c8efa41ULL;
};

template<class ContainerAllocator>
struct DataType< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wittenstein_msgs/wittenstein";
  }

  static const char* value(const ::wittenstein_msgs::wittenstein_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 fx\n"
"float64 fy\n"
"float64 fz\n"
;
  }

  static const char* value(const ::wittenstein_msgs::wittenstein_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fx);
      stream.next(m.fy);
      stream.next(m.fz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wittenstein_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wittenstein_msgs::wittenstein_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wittenstein_msgs::wittenstein_<ContainerAllocator>& v)
  {
    s << indent << "fx: ";
    Printer<double>::stream(s, indent + "  ", v.fx);
    s << indent << "fy: ";
    Printer<double>::stream(s, indent + "  ", v.fy);
    s << indent << "fz: ";
    Printer<double>::stream(s, indent + "  ", v.fz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WITTENSTEIN_MSGS_MESSAGE_WITTENSTEIN_H
